name: todo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bloc: ^5.0.0
  flutter_bloc: ^5.0.0
  equatable: ^1.0.0
  get_it: ^4.0.2
  moor: ^3.2.0
  moor_ffi: ^0.7.0
  path_provider: ^1.6.11
  path: ^1.7.0
  modal_bottom_sheet: ^0.2.0+1

dev_dependencies:
  moor_generator: ^3.2.0
  build_runner: ^1.10.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/